config/routes.rb
Rails.application.routes.draw do
    root 'pages#home'
    
    get '/home', to: 'pages#home'
    
    
    #get '/recipes', to: 'recipes#index'
    #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
    #post '/recipes', to: 'recipes#create'
    #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
    #patch '/recipes/:id', to: 'recipes#update'
    #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
    #delete '/recipes/:id', to: 'recipes#destroy'
    
    resources :recipes do
        member do
            post 'like'
        end
    end
    
    
    
end

app/models/chef.rb
class Chef < ActiveRecord::Base
    has_many :recipes
    has_many :likes
    
    before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: {minimum: 3 , maximum: 40}
    validates :email, presence: true, length: {maximum: 105}, uniqueness: { case_sensitive: false },
                        format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    has_secure_password
end

app/models/like.rb
class Like <ActiveRecord::Base
    belongs_to :chef
    belongs_to :recipe
    
    validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes
    validates :chef_id, presence: true
    validates :name, presence: true, length: {minimum: 5, maximum: 100}
    validates :summary, presence: true, length: {minimum: 10, maximum: 150}
    validates :description, presence: true, length: {minimum: 20, maximum: 500}
    mount_uploader :picture, PictureUploader
    validate :picture_size
    
    default_scope -> {order(updated_at: :desc)}
    
    def thumbs_up_total
        self.likes.where(likes: true).size
    end
    def thumbs_down_total
        self.likes.where(likes: false).size
    end
    
    private 
        def picture_size
         if picture.size > 5.megabytes
             errors.add(:picture, "shoul be less than 5mg")
         end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe::paginate(:page => params[:page], :per_page=> 4)
       
    end
    
    def show
        respond_to do | format|
            @recipe = Recipe::find(params[:id])
            format.html # show.html.erb
            format.json { render json: @recipe }
            
        end
    end
    
    def new
        @recipe = Recipe.new
    end
    def create
        @recipe = Recipe.new(recipe_param)
        @recipe.chef = Chef.find(1)
        
 
        if @recipe.save
            flash[:success] = "Your Recipe was created succesfully"
            redirect_to recipes_path
        else
            render :new
        end
    end
    def edit
        @recipe = Recipe.find(params[:id])
    end
    
    def update
        @recipe = Recipe.find(params[:id])

        if @recipe.update(recipe_param)
            flash[:success] = "Your Recipe was Edit succesfully"
            redirect_to recipe_path(@recipe)
        else
            render :new
        end
    end
    
    def like
        @recipe = Recipe.find(params[:id])
        like = Like.create(likes: params[:like], chef: Chef.first, recipe: @recipe)
        if like.valid?
            flash[:success] = "Your Selection was Succesfull"
            redirect_to :back
        else
            flash[:danger] = "You can only like/deslike a recipe once"
            redirect_to :back
        end
        
    end
    private
        
        def recipe_param
            params.require(:recipe).permit(:name,:summary,:description,:picture)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(chef,options={size: 80 })
        gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        
        image_tag(gravatar_url,alt: chef.chefname, class: "gravatar")
    end
end

app/views/layouts/_message.html.erb
<div class="row">
    <div class="col-md-10">
        <% flash.each do | message_type ,message | %>
            <div class="alert alert-<%=message_type%>">
                 <%= message %>
                 
                 <a class="close" data-dismiss="alert">&#215;</a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
     <%= link_to "MyRecipes", recipes_path, class: "btn btn-lg btn-success", id: "logo" %>
     <div class="nav_item">
         <%= link_to "Link 1", "", class: "btn  btn-warning" %>
     </div>
     <div class="nav_item">
         <%= link_to "Link 2", "", class: "btn  btn-warning" %>
     </div>
     <div class="nav_item">
         <%= link_to "Create a new Recipe", new_recipe_path, class: "btn  btn-warning" %>
     </div>
  </div>
</header>

<div class="container">
  <%= render 'layouts/message' %>
  <%= yield %>
  
  <div class="footer">
    <p>&copy; MyRecipes 2015</p>
  </div>
</div>


</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to MyRecipes Apps</h1>
    <h2>This is the home page for the professional Ruby on Rails Developer Course on Udemy</h2>
    <%= link_to "Sign up now!","", class: "btn btn-lg btn-success" %>
</div>

<div class="row">
    <div class="col-lg-4">
        <h3 class="midrow">View Recipes as Guest User</h3>
        <h2 class="left">Browse and view repices as a guest and Sign up later</h2>
        <p><%= link_to "Brpwse Recipe Listing", "", class:"btn btn-warning btn-small" %> </p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">View Recipes as Guest User</h3>
        <h2 class="left">Browse and view repices as a guest and Sign up later</h2>
        <p><%= link_to "Brpwse Recipe Listing", "", class:"btn btn-warning btn-small" %> </p>
    </div>
    <div class="col-lg-4">
        <h3 class="midrow">View Recipes as Guest User</h3>
        <h2 class="left">Browse and view repices as a guest and Sign up later</h2>
        <p><%= link_to "Browse Recipe Listing", "", class:"btn btn-warning btn-small" %> </p>
    </div>
</div>

app/views/recipes/_form.html.erb
<%= render "shared/errors", obj: @recipe %>
<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%=form_for(@recipe, html: {multipart:true}) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :summary %>
            <%= f.text_field :summary %>
            
            <%= f.label :description %>
            <%= f.text_area :description %>
            
            <span class="picture">
                <%= f.file_field :picture,accept: 'image/jpeg, image/gif, image/png' %>
            </span>
            <%= f.submit  class: "btn btn-success" %>  
        <% end %>
    </div>
</div>

app/views/recipes/edit.html.erb
<p>
    <h1>Edit Recipe</h1>
    <hr/>
</p>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<hr/>
<div class="center">
   <%= will_paginate %> 
</div>

<% @recipes.each do |d| %>
  <div class="row">
      <div class="col-md-2">
          <section class="chef_info center">
              <%=gravatar_for d.chef, size: 100 %>
              <h5>Chef Name:<%= d.chef.chefname %></h5>
          </section>
      </div>
      <div class="col-lg-6 well">
         <h4><%= link_to d.name, d %></h4>
         <p><%=d.summary%></p>
         <p>
             <span class="quiet"><small>Created:<%=time_ago_in_words(d.created_at) %> ago, </small></span>
             <span class="quiet"><small>Updated: <%=time_ago_in_words(d.updated_at) %> ago</small></span>
         </p>
          <div class="pull-right">
                <%=link_to like_recipe_path(d, like:true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> <%= d.thumbs_up_total %>
                <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
                <%=link_to like_recipe_path(d, like:false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i><%= d.thumbs_down_total %>
                <% end %>
            </div>
      </div>
      <div class="col-md-4">
          <%= image_tag(d.picture.url,size:"250x150",class:"gravatar") if d.picture? %>
      </div>
  </div>
  <hr/>
<% end %>

app/views/recipes/new.html.erb
<p>
    <h1>Create a new Recipe</h1>
    <hr/>
</p>

<%= render "form" %>

app/views/recipes/show.html.erb
<p>
    <h1><%= @recipe.name %></h1>
</p>
<div class="row">
    <div class="col-md-4 pull-right center">
        <%= gravatar_for @recipe.chef,size: 200 %>
        <p>
            <h5>Brougth to you by <%= @recipe.chef.chefname %></h5>
        </p>
    </div>
    <div class="col-md-8">
        <%= link_to "edit", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
        <h3><%= @recipe.summary %></h3>
        <div class="show_recipe">
            <%= image_tag(@recipe.picture.url, class: 'gravatar') if @recipe.picture? %>
        </div>
        <div class="well">
            <p>
                <strong>
                    steps:
                </strong>
            </p>
            <%= simple_format(@recipe.description) %>
            <div class="pull-right">
                <%=link_to like_recipe_path(@recipe, like:true), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-up"></i> <%= @recipe.thumbs_up_total %>
                <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
                <%=link_to like_recipe_path(@recipe, like:false), method: :post do %>
                    <i class="glyphicon glyphicon-thumbs-down"></i><%= @recipe.thumbs_down_total %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<h5><%= link_to "Return Recipes List", recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger col-md-8 col-md-offset-2">
        <h5>Please correct the following errors:</h5>
        <ul>
            <% obj.errors.full_messages.each do | men | %>
                <li><%=men%></li>
            <% end %>
        </ul>
    </div>
<%end%>